# -*- coding: utf-8 -*-
"""nobel_prize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aXSCLBRBwqSDtDs5t_iv3q7fwZZaFeRb
"""


import pandas as pd
url = '/content/nobel-prize-laureates.csv'
data = pd.read_csv(url, sep=';')

"""# Checking for null rows"""

data.isnull().sum()
data[data['Surname'].isna()]


"""# deleting unnecessary rows"""

data.drop(['Born city', 'Died city', 'Overall motivation', 'Geo Shape',
          'Geo Point 2D'],
          axis=1, inplace=True)


"""# Concatenating the names"""

data['Firstname'] = data.apply(
    lambda row: row['Firstname'] + ' ' + row['Surname'] if pd.notnull(
        row['Surname']
        )
    else row['Firstname'], axis=1)


data.rename(columns={'Firstname': 'Name'}, inplace=True)

"""# Deleting 'Surname' column"""
del data['Surname']

"""# Saving cleaned data"""
data.to_csv('nobel.csv', index=False, sep=';')
